// BlockOut 3000
// Copyright(c) 2018 Borislav Stanimirov
//
// Distributed under the MIT Software License
// See accompanying file LICENSE.txt or copy at
// http://opensource.org/licenses/MIT
//
#include "Resources.hpp"

namespace
{

const char* data =
"set \"Common\" # not really used as a set but has common figures\n"
"{\n"
"\tdesc \"Internal\"\n"
"\n"
"\tfigure \"Angle\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 0 1 0\n"
"\t\tc 0.5 0.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"T\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 2 0 0\n"
"\t\te 1 1 0\n"
"\t\tc 1.5 0.5 0.5\n"
"\t}\n"
"\n"
"\t# this is a 3d game... no need for a \"reverse L\"\n"
"\tfigure \"L\"\n"
"\t{\n"
"\t\te 0 2 0\n"
"\t\te 0 1 0\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\tc 0.5 1.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"Stair\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 1 1 0\n"
"\t\te 2 1 0\n"
"\t\tc 1.5 0.5 0.5\n"
"\t}\n"
"}\n"
"\n"
"set \"Basic\"\n"
"{\n"
"\tdesc \"The Soma 3x3x3 cube set\"\n"
"\n"
"\tinclude \"Common\"\n"
"\n"
"\tfigure \"Right corner\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 0 1 0\n"
"\t\te 1 0 1\n"
"\t\tc 1 1 1\n"
"\t}\n"
"\n"
"\tfigure \"Left corner\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 0 1 0\n"
"\t\te 0 1 1\n"
"\t\tc 1 1 1\n"
"\t}\n"
"\n"
"\tfigure \"Three corner\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 0 1 0\n"
"\t\te 0 0 1\n"
"\t\tc 1 1 1\n"
"\t}\n"
"}\n"
"\n"
"set \"Flat\" # the simple flat 2d set\n"
"{\n"
"\tdesc \"The simple flat set\"\n"
"\n"
"\tinclude \"Common\"\n"
"\n"
"\tfigure \"Dot\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\tc 0.5 0.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"Short I\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 0 1 0\n"
"\t\tc 0.5 0.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"I\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 0 1 0\n"
"\t\te 0 2 0\n"
"\t\tc 0.5 1.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"Square\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 1 0 0\n"
"\t\te 0 1 0\n"
"\t\te 1 1 0\n"
"\t\tc 1 1 0\n"
"\t}\n"
"}\n"
"\n"
"set \"Extended\"\n"
"{\n"
"\tinclude \"Flat\"\n"
"\tinclude \"Basic\"\n"
"\n"
"\tfigure \"4-I\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 0 1 0\n"
"\t\te 0 2 0\n"
"\t\te 0 3 0\n"
"\t\tc 0.5 1.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"5-I\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 0 1 0\n"
"\t\te 0 2 0\n"
"\t\te 0 3 0\n"
"\t\te 0 4 0\n"
"\t\tc 0.5 2.5 0.5\n"
"\t}\n"
"\n"
"\tfigure \"Long L\"\n"
"\t{\n"
"\t\te 0 0 0\n"
"\t\te 0 1 0\n"
"\t\te 0 2 0\n"
"\t\te 1 0 0\n"
"\t\te 2 0 0\n"
"\t\tc 1.5 1.5 0.5\n"
"\t}\n"
"}\n";

}

const std::string& Resources::figuresData()
{
    static const std::string d = data;
    return d;
}